#!/bin/bash

function usage {
    echo -e "Usage: megphys [COMMAND]"
    echo -e
    echo -e "Perform MegaPhysics website functions."
    echo -e
    echo -e "Commands:"
    echo -e "\tbuild\tBuild the website HTML files into 'build' directory."
    echo -e "\tserve\tServe the website to localhost:8000 using SimpleHTTPServer"
    echo -e "\tgo\tEquivalent to build and then serve"
    echo -e "\tpublish\tBuild site and publish changes to server"
    echo -e "\tclean\tRemove the 'build' directory, containing the compiled"
    echo -e "\t     \tHTML code."
    echo -e "\ttest\tTest the current build system against a reference html file"
    echo -e "\tupdate_tests\tRebuild the reference html file for testing purposes"
}

function build {
    python run.py
}

function publish {
    if git diff-index --quiet HEAD --; then
        MEGPHYS_ROOT="/MegaPhysics/" python run.py
        cp -r build /tmp/megaphysics_build
        git checkout gh-pages
        cp -r /tmp/megaphysics_build/. .
        rm -rf /tmp/megaphysics_build
        echo "Now commit your changes and push to Ap0c/MegaPhysics."
    else
        echo "You must have a clean working directory to publish."
    fi
}

function serve {
    if cd build; then
        python -m SimpleHTTPServer
        cd ..
    else
        echo "Build not found. Try running 'megphys build', or run 'megphys'"
        echo "for usage."
        exit 1
    fi
}

function go {
    build
    serve
}

function clean {
    if rm -r build; then
        echo "Successfully cleaned 'build' directory."
    else
        echo "Error cleaning 'build' directory."
        exit 1
    fi
}

function update_tests {
    python test.py
}

if [[ "$1" == "build" ]]; then build
elif [[ "$1" == "serve" ]]; then serve
elif [[ "$1" == "go" ]]; then go
elif [[ "$1" == "publish" ]]; then publish
elif [[ "$1" == "clean" ]]; then clean
elif [[ "$1" == "test" ]]; then nosetests
elif [[ "$1" == "update_tests" ]]; then update_tests
else
    usage
    exit 1
fi
